### ISSUE TITLE
Selecting provider

### ISSUE THREAD

**Issue by bluss** [frostming/findpython#17]
Previous discussion prompted this issue.

The goal is ultimately for pdm to provide an option to be more directed in finding python- from a particular provider, for example pyenv. The reason is the user wants a predictable configuration - for example, all my projects use python installed by one designated provider.

The design I'd like to propose is that

- Every provider defines its configuration name:
  - PyenvProvider.name == "pyenv"
  - PathProvider.name == "path"
  - etc

- Finder class takes a configuration input `provider_selection: list[str]`
  - Input needed: `__init__` parameter or `find` parameter? Either can work, I think.
- Only listed providers (one or more) are used for finding python
- Providers are used in the given order (if possible)

I hope this is sounds halfway reasonable or can be made reasonable

**Comment by frostming** [comment]
Sounds good, are you interested in contributing a PR?

**Comment by bluss** [comment]
Yes!
