### ISSUE TITLE
Q: why use `findpython`? 🤔

### ISSUE THREAD

**Issue by kloczek** [frostming/findpython#19]
When I found that in my set of packaged python modules as rpm packages `findpython` is not updated for switching `pdm-pdm-517` to `pdm-backend` I've started looking what is is using this module and so far found that is is used only by `pdm`.

Looking on the `pdm` code I have impression that it should be possible to replace `findpython` use by standard python modules.
Q: is this modules really needs to be used? 🤔

**Comment by frostming** [comment]
Why this question? People are free to create a package when he feels necessary, right?

> it should be possible to replace findpython use by standard python modules.

Every package is built with standard python modules, it is possible, but it is not necessary.

**Comment by kloczek** [comment]
Please .. I've not been asking about any people ..
My question had nothing to do with any personal context.

Issue is that `findpython` is not not updated and looks like it can b rep;aced by standard modules -> it could be one test and runtime dependency less -> KISS principle.

**Comment by frostming** [comment]
Let me try to understand your wants. You are asking to drop findpython since it is used by noone? Or you are a distro maintainer and don't want to package for findpython?



> Issue is that `findpython` is not not updated

What do you mean by "not updated", can't it be solved by updating it?

**Comment by kloczek** [comment]
> Let me try to understand your wants

I don't want anything.
I've asked the questions .. only this and nothing more.
Looks like you threated that question almost like personal attack (which is bizarre).

> What do you mean by "not updated", can't it be solved by updating it?

I can only reapeat what I wrote initially:

"When I found that in my set of packaged python modules as rpm packages `findpython` is **not updated** for switching `pdm-pep517` to `pdm-backend` I've started looking what is is using this module and so far found that is is used only by `pdm`."

As I wrote after brief check what is in `findpython` it looks like generally functionalities provided by `findpython` (like find python interpreter version and path to executable) are part of the standard pyton `sys` module.

**Comment by frostming** [comment]
`sys` only returns information for the **current** interpreter right? While this project, as the name implies, finds **all** interpreters installed on the system.

**Comment by kloczek** [comment]
in test suite session pytest is executed against exact python version which is used in `pytest` script and not against all possible python interpreters (`findpython ` us used in `pdm` test suite).
`pdm` is pep517 backend and calling `build` or `pip` with use pep157 it is executes exact python version not all possible pythons installed somehow in the system.
From that point of view looking for all possible pythons does not make to much sense ..

NONE of other pep517 backends (setuptools, hatchlings, whey, flint-core ..) are doing anything like trying using all installed pythons.
Q: what is the sense of doing that? 🤔

**Comment by frostming** [comment]
There seems to be large misunderstanding

> `pdm` is pep517 backend

No, it is a frontend, a development tool. Have you ever used it after all? The backend is `pdm-backend` which has fewer dependencies. PDM should be compared to Pipenv, Poetry, even tox and nox, all of which need the ability to find installed Pythons.

Your reply makes totally no sense and misunderstand both PDM and PEP 517 backends.

**Comment by kloczek** [comment]
> Your reply makes totally no sense and misunderstand both PDM and PEP 517 backends.

Second time you've skipped question to go to personal rant.
Thank you for your time. I have no other questions.
