### ISSUE TITLE
Vendoring unreleased software is suboptimal

### ISSUE THREAD

**Issue by dvzrv** [frostming/findpython#4]
Hi! I'm currently looking into packaging this software (and pdm) for Arch Linux.

The vendoring of the unreleased and seemingly abandoned [pep514tools](https://github.com/zooba/pep514tools) is suboptimal from a downstream point of view, as it makes it not possible to devendor the dependency (easily).

Would it be possible to use different tooling as direct dependency that replace the aforementioned project or to become a new stable upstream of the tooling so that there can be releases of it ([a related issue has been open since 2019](https://github.com/zooba/pep514tools/issues/5))?

**Comment by frostming** [comment]
Thanks, does it work if I absorb the vendor code into findpython's codebase? I can maintain the code onwards.

**Comment by dvzrv** [comment]
Hey! Sorry for the late reply!

This looks great, many thanks!
