### ISSUE TITLE
LegacyVersion object has no attribute major

### ISSUE THREAD

**Issue by johnbendi** [frostming/findpython#9]
LegacyVersion object returned from `packaging` module doesn't have the attributes being required from this package. There should be a check for that.

**Comment by frostming** [comment]
How do you trigger the error? Do you have any prerelease versions installed?

**Comment by frostming** [comment]
There indeed is one: https://github.com/frostming/findpython/blob/2ce66fa6ced4ce526e710ee10e42e6e855b04f7f/src/findpython/python.py#L34-L35
